name: ZombieInvasion
version: 1.0
Author: Numixe
main: me.numixe.zombieinvasion.ZombieInvasion
commands:
        zombieinvasion:
          description: Open a command.        
        zombieinvasion setspawn:
          description: List the lobby
          usage: syntax | /zombieinvasion ls
        zombieinvasion setspawn:
          description: Set new or overwrite old spawn with the current location
        zombieinvasion rmspawn:
          description: Remove an existing spawn
        zombieinvasion spawn:
          description: Teleport to hub spawn
        zombieinvasion sethub:
          description: Set the hub spawn
        zombieinvasion start:
          description: Start the game instantly
        zombieinvasion timerstart:
          description: Start the game after a 5 seconds timer
        zombieinvasion stop:
          description: Interrupt the game
        zombieinvasion villagerform:
          description: Set the form to villager
        zombieinvasion zombieform:
          description: Set the form to zombie
        zombieinvasion nullform:
          description: Set the normal form
        zombieinvasion refreshscore:
          description: Update the scoreboard data
        zombieinvasion add:
          description: Add to the game lobby